apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  env: production

resources:
  - ../../base
  - namespace.yaml

namespace: production

patches:
  - path: deployment.yaml
